CREATE TABLE IF NOT EXISTS CAMPUS_SERVICE_COUNTRY
(
    COUNTRY_ID        bigint       NOT NULL AUTO_INCREMENT,
    CREATED_AT        datetime     NOT NULL,
    CREATED_BY        varchar(255) NOT NULL,
    UPDATED_AT        datetime,
    UPDATED_BY        varchar(255),
    COUNTRY_NAME      varchar(255) NOT NULL,
    COUNTRY_ACRONYM   varchar(255) NOT NULL,
    COUNTRY_CONTINENT varchar(255) NOT NULL,
    PRIMARY KEY (COUNTRY_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS CAMPUS_SERVICE_CONTACT
(
    CONTACT_ID             bigint       NOT NULL AUTO_INCREMENT,
    CONTACT_EMAIL          varchar(255) NOT NULL,
    CONTACT_PHONE_NUMBER   varchar(255) NOT NULL,
    ADDRESS_ROAD           varchar(255) NOT NULL,
    ADDRESS_NUMBER         int          NOT NULL,
    ADDRESS_TOWN           varchar(255),
    ADDRESS_ZIPCODE        varchar(255),
    SOCIAL_MEDIA_FACEBOOK  varchar(255),
    SOCIAL_MEDIA_INSTAGRAM varchar(255),
    SOCIAL_MEDIA_LINKEDIN  varchar(255),
    SOCIAL_MEDIA_SNAPCHAT  varchar(255),
    PRIMARY KEY (CONTACT_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CAMPUS_SERVICE_REGION
(
    REGION_ID   bigint       NOT NULL AUTO_INCREMENT,
    CREATED_AT  datetime     NOT NULL,
    CREATED_BY  varchar(255) NOT NULL,
    UPDATED_AT  datetime,
    UPDATED_BY  varchar(255),
    REGION_NAME varchar(255) NOT NULL,
    PRIMARY KEY (REGION_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CAMPUS_SERVICE_TOWN
(
    TOWN_ID    bigint       NOT NULL AUTO_INCREMENT,
    CREATED_AT datetime     NOT NULL,
    CREATED_BY varchar(255) NOT NULL,
    UPDATED_AT datetime,
    UPDATED_BY varchar(255),
    TOWN_NAME  varchar(255) NOT NULL,
    COUNTRY_ID bigint       NOT NULL,
    REGION_ID  bigint,
    PRIMARY KEY (TOWN_ID),
    CONSTRAINT FK_CS_TOWN_ON_CS_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES CAMPUS_SERVICE_COUNTRY (COUNTRY_ID),
    CONSTRAINT FK_CS_TOWN_ON_CS_REGION FOREIGN KEY (REGION_ID) REFERENCES CAMPUS_SERVICE_REGION (REGION_ID)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS CAMPUS_SERVICE_CAMPUS
(
    CAMPUS_ID   bigint       NOT NULL AUTO_INCREMENT,
    CREATED_AT  datetime     NOT NULL,
    CREATED_BY  varchar(255) NOT NULL,
    UPDATED_AT  datetime,
    UPDATED_BY  varchar(255),
    CAMPUS_NAME varchar(255) NOT NULL,
    TOWN_ID     bigint       NOT NULL,
    CONTACT_ID  bigint,
    PRIMARY KEY (CAMPUS_ID),
    CONSTRAINT FK_CS_CAMPUS_ON_CS_TOWN FOREIGN KEY (TOWN_ID) REFERENCES CAMPUS_SERVICE_TOWN (TOWN_ID),
    CONSTRAINT FK_CS_CAMPUS_ON_CS_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CAMPUS_SERVICE_CONTACT (CONTACT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
