ALTER TABLE CAMPUS_SERVICE_COUNTRY
    MODIFY CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CAMPUS_SERVICE_COUNTRY
    MODIFY CREATED_BY VARCHAR(250) NOT NULL DEFAULT 'Jaivohozin';