ALTER TABLE CAMPUS_SERVICE_TOWN
    MODIFY CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CAMPUS_SERVICE_TOWN
    MODIFY CREATED_BY VARCHAR(250) NOT NULL DEFAULT 'Jaivohozin';

ALTER TABLE CAMPUS_SERVICE_CAMPUS
    MODIFY CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CAMPUS_SERVICE_CAMPUS
    MODIFY CREATED_BY VARCHAR(250) NOT NULL DEFAULT 'Jaivohozin';

ALTER TABLE CAMPUS_SERVICE_REGION
    MODIFY CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CAMPUS_SERVICE_REGION
    MODIFY CREATED_BY VARCHAR(250) NOT NULL DEFAULT 'Jaivohozin';